"""
Django settings for quickstartproject project.

Generated by 'django-admin startproject' using Django 5.1.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '1234567890'

# 22-10-2025 - loading variables for Django Secret Key + MySQL info
from dotenv import load_dotenv
load_dotenv()

# 15-10-2025 - For working with databases at Render and Neon Cloud
import dj_database_url

# 15-10-2025 - For working with databases at Render and Neon Cloud
DATABASE_URL=os.getenv('DATABASE_URL')

# Getting the secret key from env locally and from enviroment variable in production
SECRET_KEY=os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# With DEBUG=False 404 errors will be directed to a default 404 template
# Not: Django will display a 404.html if you have created one :-)
DEBUG = False

# 17-05-2026 - Needed for locally developing but dont work at Azure !
# DEVELOPEMENT - Disable for Production !
# ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# 17-05-2026 - Needed for Azure but dont work when running locally developing !
# PRODUCTION - Disable for Developement !
ALLOWED_HOSTS = ['pso-django.azurewebsites.net']

# 22-10-2025 - Needed at Azure to avoid 403 forbidden when trying to login to the Django Admin Backend
# PRODUCTION - Disable for Developement !
CSRF_TRUSTED_ORIGINS = ['https://pso-django.azurewebsites.net']

# Application definition
INSTALLED_APPS = [

    # 21-10-2025 - For Azure
    "whitenoise.runserver_nostatic",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # For serving static files
    'django.contrib.staticfiles',
    'example'
]

MIDDLEWARE = [
    
    # For serving all kind of static files in a correct way use Debug = False
    # This setting is neeeded for serving static files frontend and backend admin
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         
         # Added the URL for work with templates
         # Initially create the dir 'templates' at root level
         # Root level is fine because there is only one Django App in the Project
         'DIRS': [],
         #'DIRS': [BASE_DIR / 'templates'],

         # 21-10-2025 - Test for Azure
        # 'DIRS': [ os.path.join(BASE_DIR, 'templates') ],
        

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 21-10-2025 - For Azure - "application" match in asgi.py as well as wsgi.py
WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Note: Django modules for using databases are not support in serverless
# environments like Vercel. You can use a database over HTTP, hosted elsewhere.

# 18-10-2025 - The SQLite works both locally and uploaded to Pythonanywhere 
'''DATABASES = {

'default': {
   'ENGINE': 'django.db.backends.sqlite3',
   'NAME': BASE_DIR / "db.sqlite3",
  }

}'''


# No Database needed for this Starter
# DATABASES = { }

# 17-05-2026 - PostgreSQL with a Serverless setup at Neon Cloud
DATABASES = {

    'default': dj_database_url.config(

        default=DATABASE_URL,

        conn_max_age=600,
        ssl_require=True, 
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# 21-10-2025 - Works at Azure but dont work when running locally developing !
# STATICFILES_DIRS = (str(BASE_DIR.joinpath('static')),)

# 21-10-2025 - Needed for locally developing and seems to work at Azure too !
STATICFILES_DIRS = (str(BASE_DIR.joinpath('assets')),)

# Works both locally and at Azure
STATIC_URL = 'static/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 21-10-2025 - Works at Azure but dont work when running locally developing !
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 21-10-2025 - Needed for locally developing and seems to work at Azure too !
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------
# Note: Run the below command before deployment:
# python manage.py check --deploy
# Azure HTTPS security hardening (enable for production)
#
# Uncomment when moving from demo to stricter production settings:
#
# SECURE_PROXY_SSL_HEADER = (
#     "HTTP_X_FORWARDED_PROTO",
#     "https",
# )
#
# SECURE_SSL_REDIRECT = True
#
# SESSION_COOKIE_SECURE = True
#
# CSRF_COOKIE_SECURE = True
#
# SECURE_HSTS_SECONDS = 3600
# -------------------------------------------------------------------
